/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hudson_plugins_vmware_vix_VMWareVIX */

#ifndef _Included_hudson_plugins_vmware_vix_VMWareVIX
#define _Included_hudson_plugins_vmware_vix_VMWareVIX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hudson_plugins_vmware_vix_VMWareVIX
 * Method:    vixHostConnect
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_hudson_plugins_vmware_vix_VMWareVIX_vixHostConnect
  (JNIEnv *, jclass, jstring, jstring, jstring, jint);

/*
 * Class:     hudson_plugins_vmware_vix_VMWareVIX
 * Method:    vixHostDisconnect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hudson_plugins_vmware_vix_VMWareVIX_vixHostDisconnect
  (JNIEnv *, jclass, jint);

/*
 * Class:     hudson_plugins_vmware_vix_VMWareVIX
 * Method:    vixHostRegisterVM
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hudson_plugins_vmware_vix_VMWareVIX_vixHostRegisterVM
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hudson_plugins_vmware_vix_VMWareVIX
 * Method:    vixHostUnregisterVM
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hudson_plugins_vmware_vix_VMWareVIX_vixHostUnregisterVM
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hudson_plugins_vmware_vix_VMWareVIX
 * Method:    vixVMOpen
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hudson_plugins_vmware_vix_VMWareVIX_vixVMOpen
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hudson_plugins_vmware_vix_VMWareVIX
 * Method:    vixVMPowerOn
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hudson_plugins_vmware_vix_VMWareVIX_vixVMPowerOn
  (JNIEnv *, jclass, jint);

/*
 * Class:     hudson_plugins_vmware_vix_VMWareVIX
 * Method:    vixVMPowerOff
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hudson_plugins_vmware_vix_VMWareVIX_vixVMPowerOff
  (JNIEnv *, jclass, jint);

/*
 * Class:     hudson_plugins_vmware_vix_VMWareVIX
 * Method:    vixVMSuspend
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hudson_plugins_vmware_vix_VMWareVIX_vixVMSuspend
  (JNIEnv *, jclass, jint);

/*
 * Class:     hudson_plugins_vmware_vix_VMWareVIX
 * Method:    vixVMReset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hudson_plugins_vmware_vix_VMWareVIX_vixVMReset
  (JNIEnv *, jclass, jint);

/*
 * Class:     hudson_plugins_vmware_vix_VMWareVIX
 * Method:    vixVMWaitForToolsInGuest
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_hudson_plugins_vmware_vix_VMWareVIX_vixVMWaitForToolsInGuest
  (JNIEnv *, jclass, jint);

/*
 * Class:     hudson_plugins_vmware_vix_VMWareVIX
 * Method:    vixGetProperties
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hudson_plugins_vmware_vix_VMWareVIX_vixGetProperties
  (JNIEnv *, jclass, jint);

/*
 * Class:     hudson_plugins_vmware_vix_VMWareVIX
 * Method:    vixGetErrorText
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hudson_plugins_vmware_vix_VMWareVIX_vixGetErrorText
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     hudson_plugins_vmware_vix_VMWareVIX
 * Method:    vixVMLoginGuest
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hudson_plugins_vmware_vix_VMWareVIX_vixVMLoginGuest
  (JNIEnv *, jclass, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
